### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by dtcyad1** [cozimacode/react-bot#1]
Hi Naser,

really great bot!! I am having difficulty adding a scroll bar. Is there a way to add the scroll bar - keeping the responsive design in place?

Thanks
-yogesh

**Comment by cozimacode** [comment]
Hi @dtcyad1,

The scroll bar was hidden for aesthetic reasons. You can show it again by overriding/removing `-ms-overflow-style` and `scrollbar-width` in class `rcb-conversation` and deleting the pseudo-element `.rcb-conversation::-webkit-scrollbar` from styles.css

![image](https://user-images.githubusercontent.com/56202963/110198365-f9acee00-7e77-11eb-843f-1e62492d842f.png)

Please close this if your issue was resolved. Glad you liked the bot :)

**Comment by dtcyad1** [comment]
Hi Naser,

Appreciate the fast response. The fix works great. Thanks so much. Closing the issue.
